const notificationController = require("../controllers/notification");
const { isValidId, authJwt, objectId } = require("../middlewares");
const express = require("express");
const router = express.Router();
    router.post( "/admin/anotifications", [authJwt.isAdmin], notificationController.sendNotifications);
    router.get( "/admin/anotifications", [authJwt.isAdmin], notificationController.getAllNotifications);
    router.get( "/admin/anotifications/:id", [authJwt.isAdmin], notificationController.getNotificationById);
    router.delete( "/admin/anotifications/:id", [authJwt.isAdmin], notificationController.deleteNotificationById);
    router.get( "/anotifications", [authJwt.verifyToken], notificationController.getAllNotifications);
    router.get( "/anotifications/:id", [authJwt.verifyToken, objectId.validId], notificationController.getNotificationById);
    module.exports = router;
