const notificationController = require("../controllers/notification");
const { isValidId, authJwt, objectId } = require("../middlewares");
const express = require("express");
const router = express.Router();
    router.post( "api/v1/admin/anotifications", [authJwt.isAdmin], notificationController.sendNotifications);
    router.get( "api/v1/admin/anotifications", [authJwt.isAdmin], notificationController.getAllNotifications);
    router.get( "api/v1/admin/anotifications/:id", [authJwt.isAdmin], notificationController.getNotificationById);
    router.delete( "api/v1/admin/anotifications/:id", [authJwt.isAdmin], notificationController.deleteNotificationById);
    router.get( "api/v1/anotifications", [authJwt.verifyToken], notificationController.getAllNotifications);
    router.get( "api/v1//anotifications/:id", [authJwt.verifyToken, objectId.validId], notificationController.getNotificationById);
    module.exports = router;
